security:
  basic:
    enabled: false

management:
  security:
    enabled: false

logging: # <----New sections below
  level:
    io:
      pivotal: ERROR

greeting:
  displayFortune: false

quoteServiceURL: http://quote-service-dev.cfapps.io/quote